---
title: "**SteamDB Analysis**"
author: "***Vitalii Morskyi*** -- 166731 | L4 | 2FS-DI"

output:
    html_document: default
    ioslides_presentation: default
---

```{r}
library(tidyverse)
library(forecast)
library(timeDate)
library(lubridate)
library(lattice)
PATH <- "D:/"
```

# **Data**
```{r}
df <- read.csv(paste0(PATH, "SteamDB.csv"),
               na.strings = "",
               sep = ";",
               header = TRUE,
               col.names = c("DateTime", "Users", "InGame"))
df$DateTime <- as.POSIXct(df$DateTime, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
# df$type <- as.factor(df$type)
df.18_21 <- df[c(which(df$DateTime == make_datetime(year = 2018)):(which(df$DateTime == make_datetime(year = 2022)) - 1)), ]
head(df.18_21, 10)
```
```{r}
summary(df.18_21)
```
```{r}
users <- ts(df$Users, start = c(2004, 13), frequency = 365)
ingame <- ts(df$InGame, start = c(2004, 13), frequency = 365)

users.18_21 <- ts(df.18_21$Users, start = 2018, frequency = 365)
ingame.18_21 <- ts(df.18_21$InGame, start = 2018, frequency = 365)
users.18_21.f7 <- na.interp(ts(df.18_21$Users, start = 2018, frequency = 7), lambda = "auto")
par(mfrow=c(2, 1))
plot(users.18_21)
plot(ingame.18_21)
```
```{r}
boxplot(users.18_21.f7 ~ cycle(users.18_21.f7))
```
```{r}
lag.plot(users.18_21.f7, lags= 16, do.lines=FALSE, labels=FALSE)
```
```{r}
Acf(users.18_21.f7, lag.max = 100)
```
```{r}
users.18_21.f7.DecA <- decompose(users.18_21.f7, type = "additive")
plot(users.18_21.f7.DecA)
```
```{r}
users.18_21.f7.DecM <- decompose(users.18_21.f7, type = "multiplicative")
plot(users.18_21.f7.DecM)
```
```{r}
par(mfrow=c(2, 1))
plot(users.18_21.f7.DecA$random)
plot(users.18_21.f7.DecM$random)
```
```{r}
df.2weeks <- read.csv(paste0(PATH, "SteamDBWeek.csv"),
                      na.strings = "",
                      sep = ";",
                      header = TRUE,
                      col.names = c("DateTime", "Users", "UsersTrend", "InGame"))
df.2weeks$DateTime <- as.POSIXct(df.2weeks$DateTime, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
head(df.2weeks, 10)
```

```{r}
timestep <- as.numeric(df.2weeks$DateTime[2] - df.2weeks$DateTime[1], "hours")
users.2weeks <- ts(df.2weeks$Users, start = 0, frequency = 7 * 24 / timestep)
ingame.2weeks <- ts(df.2weeks$InGame, start = 0, frequency = 7 * 24 / timestep)
users.2weeks.s6 <- ts(df.2weeks$Users[seq(1, dim(df.2weeks)[1], by=6)], start = 0, frequency = 7 * 24 / timestep / 6)

par(mfrow=c(2, 1))
plot(users.2weeks.s6)
plot(ingame.2weeks)

```
```{r}
autolambda <- BoxCox.lambda(users.2weeks)
users.2weeks.BC <- BoxCox(users.2weeks, lambda = autolambda)
par(mfrow=c(2, 1))
plot(users.2weeks)
plot(users.2weeks.BC)
```
```{r}
tsdisplay(users.2weeks.BC, lag.max = 500)
```
```{r}
tsdisplay(users.2weeks.BC, lag.max = 24 / timestep)
```
```{r}
users.2weeks.BC.Diff144 <- diff(users.2weeks.BC, lag = 144)
users.2weeks.BC.Diff <- diff(users.2weeks.BC.Diff144, lag = 1)
tsdisplay(users.2weeks.BC.Diff)
```
```{r}
users.2weeks.BC.DecA <- decompose(users.2weeks.BC, type = "additive")
plot(users.2weeks.BC.DecA)
```
```{r}
users.2weeks.BC.DecM <- decompose(users.2weeks.BC, type = "multiplicative")
plot(users.2weeks.BC.DecM)
```
```{r}
users.2weeks.BC.DecMSA <- seasadj(users.2weeks.BC.DecM)
plot(users.2weeks.BC, lty = 1)
lines(users.2weeks.BC.DecMSA, col = "blue", lty = 3)
```
```{r}
users.2weeks.BC.TSlm <- tslm(users.2weeks.BC ~ trend + season)
plot(users.2weeks.BC, lty = 1)
lines(fitted(users.2weeks.BC.TSlm), col = "blue", lty = 3)
```
```{r}
plot(users.2weeks.BC.TSlm$residuals)
```
```{r}
users.2weeks.BC.Diff.ar <- ar(users.2weeks.BC.Diff, aic = FALSE, order.max = 24 / timestep, method = "yule-walker")
users.2weeks.BC.Diff.ar.for <- forecast(users.2weeks.BC.Diff.ar, h = 2000, level=95)

inverse.stationary <- function(series) {
  series.inv <- diffinv(series,
                        differences=1, 
                        lag=1, 
                        xi=users.2weeks.BC.Diff144[length(users.2weeks.BC.Diff144)])
  series.inv <- diffinv(series.inv, 
                        differences=1, 
                        lag=144, 
                        xi=users.2weeks.BC[(length(users.2weeks.BC)-143):(length(users.2weeks.BC)-0)])
  series.inv <- InvBoxCox(series.inv, lambda = autolambda)
}

users.2weeks.BC.Diff.ar.for.inv.x <- inverse.stationary(users.2weeks.BC.Diff.ar.for$mean)
plot(ts(c(users.2weeks, users.2weeks.BC.Diff.ar.for.inv.x), start = start(users.2weeks), frequency = frequency(users.2weeks)))
```
```{r}
Pacf(users.2weeks.s6, lag.max = 40)
Acf(users.2weeks.s6, lag.max = 40)
```

```{r}
users.2weeks.BC.Diff.ArimaA <- auto.arima(users.2weeks.s6, ic = "aicc")
users.2weeks.BC.Diff.ArimaA
```
```{r}
users.2weeks.BC.Diff.Arima24.1.21 <- Arima(users.2weeks.s6,order = c(24,1,21))
users.2weeks.BC.Diff.Arima24.1.2 <- Arima(users.2weeks.s6,order = c(24,1,2))
users.2weeks.BC.Diff.Arima24.1.0 <- Arima(users.2weeks.s6,order = c(24,1,0))
users.2weeks.BC.Diff.Arima24.1.21
```


```{r}
autoplot(forecast(users.2weeks.BC.Diff.Arima24.1.21, h=100))
autoplot(forecast(users.2weeks.BC.Diff.Arima24.1.2, h=100))
autoplot(forecast(users.2weeks.BC.Diff.Arima24.1.0, h=100))
autoplot(forecast(users.2weeks.BC.Diff.ArimaA, h=100))
```

